package com.example.common;

public enum PageType {
	HOME_MANAGEMENT_PAGE, MENU_MANAGEMENT_PAGE, PRODUCT_MANAGEMENT_PAGE, DETAILPRODUCT_MANAGEMENT_PAGE,
	ADMIN_MANAGER_PRODUCT,EIDT_PRODUCT,INSERT_PRODUCT,DELETE_PRODUCT,
	LOGIN_REGISTERED_PAGE,
	CART,PAYMENT


}
